# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ImageName: '$(Build.Repository.Name):$(Build.BuildId)'
  name: SNYK_API
  value: "https://snyk.io/api"
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'https://api.snyk.io/api/v1/'
        testType: 'container'
        dockerfilePath: 'Dockerfile'
        monitorWhen: 'always'
        failOnIssues: true
        projectName: 'DockerTask'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'joelanto / docker_10'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: CmdLine@2
      inputs:
        script: |
          docker version
          docker login